var movementData0 = {
	"AD" : 'notreq',
	"AE" : 'notreq',
	"AF" : 'req',
	"AG" : 'notreq',
	"AI" : 'notreq',
	"AL" : 'notreq',
	"AM" : 'notreq',
	"AO" : 'req',
	"AR" : 'notreq',
	"AS" : 'req',
	"AT" : 'freedom',
	"AU" : 'evisa',
	"AW" : 'notreq',
	"AX" : 'notreq',
	"AZ" : 'req',
	"BA" : 'notreq',
	"BB" : 'notreq',
	"BD" : 'voa',
	"BE" : 'freedom',
	"BF" : 'voa',
	"BG" : 'freedom',
	"BH" : 'voa',
	"BI" : 'voa',
	"BJ" : 'req',
	"BL" : 'freedom',
	"BN" : 'notreq',
	"BO" : 'notreq',
	"BM" : 'notreq',
	"BQ" : 'notreq',
	"BR" : 'notreq',
	"BS" : 'notreq',
	"BT" : 'preappvoa',
	"BV" : 'freedom',
	"BW" : 'notreq',
	"BY" : 'req',
	"BZ" : 'notreq',
	"CA" : 'evisa',
	"CC" : 'evisa',
	"CD" : 'req',
	"CF" : 'req',
	"CG" : 'req',
	"CH" : 'freedom',
	"CI" : 'evisa',
	"CK" : 'notreq',
	"CL" : 'notreq',
	"CM" : 'preappvoa',
	"CN" : 'req',
	"CO" : 'notreq',
	"CR" : 'notreq',
	"CU" : 'req',
	"CV" : 'voa',
	"CW" : 'notreq',
	"CX" : 'evisa',
	"CY" : 'freedom',
	"CZ" : 'freedom',
	"DE" : 'freedom',
	"DJ" : 'voa',
	"DK" : 'freedom',
	"DM" : 'notreq',
	"DO" : 'notreq',
	"DT-CR" : 'req',
	"DZ" : 'req',
	"EC" : 'notreq',
	"EG" : 'voa',
	"EE" : 'freedom',
	"EH" : 'notreq',
	"ER" : 'preappvoa',
	"ES" : 'freedom',
	"ET" : 'voa',
	"FI" : 'freedom',
	"FJ" : 'notreq',
	"FK" : 'voa',
	"FM" : 'notreq',
	"FO" : 'notreq',
	"FR" : 'freedom',
	"GA" : 'evisa',
	"GB" : 'freedom',
	"GE" : 'notreq',
	"GD" : 'notreq',
	"GF" : 'freedom',
	"GG" : 'notreq',
	"GH" : 'preappvoa',
	"GI" : 'notreq',
	"GL" : 'notreq',
	"GM" : 'notreq',
	"GN" : 'req',
	"GO" : 'nodata',
	"GP" : 'freedom',
	"GQ" : 'req',
	"GR" : 'freedom',
	"GS" : 'preappvoa',
	"GT" : 'notreq',
	"GU" : 'evisa',
	"GW" : 'voa',
	"GY" : 'notreq',
	"HK" : 'notreq',
	"HM" : 'req',
	"HN" : 'notreq',
	"HR" : 'freedom',
	"HT" : 'notreq',
	"HU" : 'freedom',
	"ID" : 'notreq',
	"IE" : 'freedom',
	"IL" : 'notreq',
	"IM" : 'notreq',
	"IN" : 'evisa',
	"IO" : 'notreq',
	"IQ" : 'req',
	"IR" : 'voa',
	"IS" : 'freedom',
	"IT" : 'freedom',
	"JE" : 'notreq',
	"JM" : 'notreq',
	"JO" : 'notreq',
	"JP" : 'notreq',
	"JU" : 'nodata',
	"KE" : 'evisa',
	"KG" : 'notreq',
	"KH" : 'voa',
	"KI" : 'notreq',
	"KM" : 'voa',
	"KN" : 'notreq',
	"KP" : 'req',
	"KR" : 'notreq',
	"XK" : 'notreq',
	"KW" : 'voa',
	"KY" : 'notreq',
	"KZ" : 'preappvoa',
	"LA" : 'voa',
	"LB" : 'voa',
	"LC" : 'notreq',
	"LI" : 'freedom',
	"LK" : 'evisa',
	"LR" : 'preappvoa',
	"LS" : 'notreq',
	"LT" : 'freedom',
	"LU" : 'freedom',
	"LV" : 'freedom',
	"LY" : 'preappvoa',
	"MA" : 'notreq',
	"MC" : 'notreq',
	"MD" : 'notreq',
	"MG" : 'notreq',
	"ME" : 'notreq',
	"MF" : 'freedom',
	"MH" : 'notreq',
	"MK" : 'notreq',
	"ML" : 'req',
	"MO" : 'notreq',
	"MM" : 'evisa',
	"MN" : 'req',
	"MP" : 'notreq',
	"MQ" : 'freedom',
	"MR" : 'voa',
	"MS" : 'notreq',
	"MT" : 'freedom',
	"MU" : 'notreq',
	"MV" : 'voa',
	"MW" : 'notreq',
	"MX" : 'notreq',
	"MY" : 'notreq',
	"MZ" : 'voa',
	"NA" : 'notreq',
	"NC" : 'freedom',
	"NE" : 'req',
	"NF" : 'evisa',
	"NG" : 'preappvoa',
	"NI" : 'notreq',
	"NL" : 'freedom',
	"NO" : 'freedom',
	"NP" : 'voa',
	"NR" : 'req',
	"NU" : 'voa',
	"NZ" : 'notreq',
	"OM" : 'voa',
	"PA" : 'notreq',
	"PE" : 'notreq',
	"PF" : 'freedom',
	"PG" : 'voa',
	"PH" : 'notreq',
	"PK" : 'req',
	"PL" : 'freedom',
	"PM" : 'freedom',
	"PN" : 'notreq',
	"PR" : 'evisa',
	"PS" : 'notreq',
	"PT" : 'freedom',
	"PW" : 'voa',
	"PY" : 'notreq',
	"QA" : 'voa',
	"RE" : 'freedom',
	"RO" : 'freedom',
	"RS" : 'notreq',
	"RU" : 'req',
	"RW" : 'evisa',
	"SA" : 'req',
	"SB" : 'notreq',
	"SC" : 'notreq',
	"SD" : 'req',
	"SE" : 'freedom',
	"SG" : 'notreq',
	"SH" : 'preappvoa',
	"SI" : 'freedom',
	"SJ" : 'preappvoa',
	"SK" : 'freedom',
	"SL" : 'preappvoa',
	"SM" : 'notreq',
	"SN" : 'notreq',
	"SO" : 'voa',
	"SR" : 'req',
	"SS" : 'req',
	"ST" : 'notreq',
	"SV" : 'notreq',
	"SX" : 'notreq',
	"SY" : 'req',
	"SZ" : 'notreq',
	"TC" : 'notreq',
	"TD" : 'req',
	"TF" : 'req',
	"TG" : 'voa',
	"TH" : 'notreq',
	"TJ" : 'voa',
	"TK" : 'preappvoa',
	"TL" : 'voa',
	"TM" : 'preappvoa',
	"TN" : 'notreq',
	"TO" : 'notreq',
	"TR" : 'evisa',
	"TT" : 'notreq',
	"TV" : 'notreq',
	"TW" : 'notreq',
	"TZ" : 'voa',
	"UA" : 'notreq',
	"UG" : 'notreq',
	"UM-DQ" : 'req',
	"UM-FQ" : 'req',
	"UM-HQ" : 'req',
	"UM-JQ" : 'req',
	"UM-MQ" : 'req',
	"UM-WQ" : 'req',
	"US" : 'evisa',
	"UY" : 'notreq',
	"UZ" : 'preappvoa',
	"VA" : 'notreq',
	"VC" : 'notreq',
	"VE" : 'notreq',
	"VG" : 'notreq',
	"VI" : 'evisa',
	"VN" : 'req',
	"VU" : 'notreq',
	"WF" : 'freedom',
	"WS" : 'notreq',
	"YE" : 'req',
	"YT" : 'freedom',
	"ZA" : 'notreq',
	"ZM" : 'notreq',
	"ZW" : 'voa'
};

var commentsData0 = {
	"AD" : '',
	"AE" : '30 days',
	"AF" : '',
	"AG" : '1 month',
	"AI" : 'Visa not required for 3 months.',
	"AL" : '90 days',
	"AM" : '180 days',
	"AO" : '',
	"AR" : '90 days',
	"AS" : 'Visa required (entry permit).',
	"AT" : 'Freedom of movement',
	"AU" : '90 days on each visit in 12-month period if granted',
	"AW" : 'Visa not required for 30 days.',
	"AX" : 'If you wish to stay in Åland longer in order to work or study, there are special rules and regulations that apply.',
	"AZ" : '',
	"BA" : '90 days within 180 days',
	"BB" : '6 months',
	"BD" : '30 days. Not available at all entry points.',
	"BE" : 'Freedom of movement',
	"BF" : '1 month',
	"BG" : 'Freedom of movement',
	"BH" : '3 months',
	"BI" : '3 months',
	"BJ" : '',
	"BL" : 'Nationals of the EU countries can enter and reside for an unlimited period without a visa in the French overseas departments and territories.',
	"BN" : '90 days',
	"BO" : '90 days',
	"BM" : 'Visa not required for 21 days (extendable).',
	"BQ" : 'Visa not required for 3 months.',
	"BR" : '90 days, extendable once',
	"BS" : '3 months',
	"BT" : 'Pre-approved visa can be picked up on arrival.',
	"BV" : 'Freedom of movement',
	"BW" : '90 days per year',
	"BY" : 'Visas are issued on arrival at the Minsk International Airport if the support documents were submitted not later than 3 business days before expected date of arrival.',
	"BZ" : '1 month',
	"CA" : '6 months; eTA required if arriving by air from 15 March 2016.',
	"CC" : '90 days on each visit in 12-month period if granted',
	"CD" : '',
	"CF" : '',
	"CG" : '',
	"CH" : 'Freedom of movement',
	"CI" : '3 months; eVisa holders must arrive via Port Bouet Airport.',
	"CK" : 'Visa free access for 31 days.',
	"CL" : '90 days',
	"CM" : 'Pre-approved visa can be picked up on arrival.',
	"CN" : '72-hours visa free visit when in transit at Beijing, Chengdu, Chongqing, Dalian, Guangzhou, Guilin, Shanghai, Shenyang and Xi\'an.',
	"CO" : 'up to 180 days',
	"CR" : '90 days',
	"CU" : '',
	"CV" : 'Not available at all entry points.',
	"CW" : 'Visa not required for 3 months.',
	"CX" : '90 days on each visit in 12-month period if granted',
	"CY" : 'Freedom of movement',
	"CZ" : 'Freedom of movement',
	"DE" : 'Freedom of movement',
	"DJ" : 'Not available at all entry points.',
	"DK" : 'Freedom of movement (DK)',
	"DM" : '3 months',
	"DO" : '90 days (10 USD Tourist Card valid for 30 days must be purchased upon arrival)',
	"DT-CR" : 'Visa issued by Russia is required.',
	"DZ" : '',
	"EC" : '90 days',
	"EG" : '30 days',
	"EE" : 'Freedom of movement',
	"EH" : 'Visa not required up to 3 months.',
	"ER" : 'Pre-approved visa can be picked up on arrival.',
	"ES" : 'Freedom of movement',
	"ET" : 'Not available at all entry points.',
	"FI" : 'Freedom of movement',
	"FJ" : '4 months',
	"FK" : 'Visitor Permit valid for 4 weeks is issued on arrival.',
	"FM" : '30 days',
	"FO" : 'Visa not required.',
	"FR" : 'Freedom of movement',
	"GA" : 'Electronic visa holders must arrive via Libreville International Airport.',
	"GB" : 'Freedom of movement (in Constituent countries)',
	"GE" : '90 days within 180 days',
	"GD" : '3 months.',
	"GF" : 'Nationals of the EU countries can enter and reside for an unlimited period without a visa in the French overseas departments and territories.',
	"GG" : 'Visa not required.',
	"GH" : 'Pre-approved visa can be picked up on arrival.',
	"GI" : 'Visa not required.',
	"GL" : 'Visa not required.',
	"GM" : '90 days',
	"GN" : '',
	"GO" : '',
	"GP" : 'Nationals of the EU countries can enter and reside for an unlimited period without a visa in the French overseas departments and territories.',
	"GQ" : '',
	"GR" : 'Freedom of movement',
	"GS" : 'Pre-arrival permit from the Commissioner required (72 hours/1 month for 110/160 pounds sterling).',
	"GT" : '90 days',
	"GU" : 'Visa not required under the Visa Waiver Program, for 90 days on arrival from overseas for 2 years. ESTA required.',
	"GW" : '90 days',
	"GY" : '3 months',
	"HK" : 'Visa not required for 90 days.',
	"HM" : 'Special permit to enter and undertake activities in the Territory of Heard Island and McDonald Islands is required and is issued by the Australian Antarctic Division.',
	"HN" : '3 months',
	"HR" : 'Freedom of movement',
	"HT" : '90 days',
	"HU" : 'Freedom of movement',
	"ID" : '30 days. Not available at all entry points.',
	"IE" : '',
	"IL" : '3 months',
	"IM" : 'Visa not required.',
	"IN" : '30 days',
	"IO" : 'Visa not required.',
	"IQ" : '',
	"IR" : '30 days',
	"IS" : 'Freedom of movement',
	"IT" : 'Freedom of movement',
	"JE" : 'Visa not required.',
	"JM" : '90 days',
	"JO" : 'Conditions apply. Not available at all entry points.',
	"JP" : '90 days, extendable once',
	"JU" : '',
	"KE" : '3 months; also visa on arrival until 1 September 2015',
	"KG" : '60 days',
	"KH" : '30 days. Visa is also obtainable online.',
	"KI" : '30 days',
	"KM" : '',
	"KN" : '3 months',
	"KP" : '',
	"KR" : '90 days',
	"XK" : 'Visa free for 90 days.',
	"KW" : '3 months',
	"KY" : 'Visa not required for 6 months.',
	"KZ" : 'Pre-approved visa can be picked up on arrival.',
	"LA" : '30 days. Not available at all entry points.',
	"LB" : '1 month extendable for 2 additional months; granted free of charge at Beirut International Airport or any other port of entry if there is no Israeli visa or seal, holding a telephone number, an address in Lebanon, and a non refundable return or circle trip ticket.',
	"LC" : '6 weeks',
	"LI" : 'Freedom of movement',
	"LK" : '30 days',
	"LR" : 'Pre-approved visa can be picked up on arrival.',
	"LS" : '90 days',
	"LT" : 'Freedom of movement',
	"LU" : 'Freedom of movement',
	"LV" : 'Freedom of movement',
	"LY" : 'Pre-approved visa can be picked up on arrival.',
	"MA" : '3 months',
	"MC" : '',
	"MD" : '90 days',
	"MG" : '30 days',
	"ME" : '90 days within 180 days',
	"MF" : 'Nationals of the EU countries can enter and reside for an unlimited period without a visa in the French overseas departments and territories.',
	"MH" : '90 days',
	"MK" : '90 days within 180 days',
	"ML" : '',
	"MO" : 'Visa not required for 90 days.',
	"MM" : '28 days, eVisa holders must arrive via Yangon, Nay Pyi Taw or Mandalay airports.',
	"MN" : '',
	"MP" : 'Visa not required.',
	"MQ" : 'Nationals of the EU countries can enter and reside for an unlimited period without a visa in the French overseas departments and territories.',
	"MR" : '',
	"MS" : 'Visa not required for 6 months.',
	"MT" : 'Freedom of movement',
	"MU" : '90 days',
	"MV" : '30 days',
	"MW" : '90 days',
	"MX" : '180 days',
	"MY" : '3 months',
	"MZ" : '30 days',
	"NA" : '3 months',
	"NC" : 'Nationals of the EU countries can enter and reside for an unlimited period without a visa in the French overseas departments and territories.',
	"NE" : '',
	"NF" : 'All visitors require a passport. All visitors require an Australian visa except for persons travelling on an Australian or New Zealand passport or persons holding a passport endorsed with Permanent Resident of Norfolk Island visa label.',
	"NG" : 'Pre-approved visa can be picked up on arrival.',
	"NI" : '90 days',
	"NL" : 'Freedom of movement (European Netherlands)',
	"NO" : 'Freedom of movement',
	"NP" : '90 days. Not available at all entry points.',
	"NR" : '',
	"NU" : 'Visa on arrival valid for 30 days is issued free of charge.',
	"NZ" : '3 months',
	"OM" : '30 days',
	"PA" : '180 days',
	"PE" : 'up to 183 days',
	"PF" : 'Nationals of the EU countries can enter and reside for an unlimited period without a visa in the French overseas departments and territories.',
	"PG" : '60 days',
	"PH" : '30 days',
	"PK" : 'Visa on arrival when travelling on business valid for 30 days. Conditions apply.',
	"PL" : 'Freedom of movement',
	"PM" : 'Nationals of the EU countries can enter and reside for an unlimited period without a visa in the French overseas departments and territories.',
	"PN" : '14 days visa free and landing fee 35 USD or tax of 5 USD if not going ashore.',
	"PR" : 'Visa not required under the Visa Waiver Program, for 90 days on arrival from overseas for 2 years. ESTA required.',
	"PS" : 'Visa not required. Arrival by sea to Gaza Strip not allowed.',
	"PT" : 'Freedom of movement',
	"PW" : '30 days',
	"PY" : '90 days',
	"QA" : '1 month. Not available at all entry points.',
	"RE" : 'Nationals of the EU countries can enter and reside for an unlimited period without a visa in the French overseas departments and territories.',
	"RO" : 'Freedom of movement',
	"RS" : '90 days within 180 days',
	"RU" : '',
	"RW" : '90 days',
	"SA" : '',
	"SB" : '3 months',
	"SC" : '1 month',
	"SD" : '',
	"SE" : 'Freedom of movement',
	"SG" : '90 days',
	"SH" : 'Ascension Island : Entry Permit must be obtained minimum 28 days in advance (3 months for 20/30 pounds sterling, single/double entry). Saint Helena : Entry Permit (£25) for 183 days is issued on arrival. Tristan da Cunha : Permission to land required for 15/30 pounds sterling (yacht/ship passenger) for Tristan da Cunha Island or 20 pounds sterling for Gough Island, Inaccessible Island or Nightingale Islands.',
	"SI" : 'Freedom of movement',
	"SJ" : 'Permit issued by the local police required for staying for less than 24 hours and permit issued by the Norwegian police for staying for more than 24 hours.',
	"SK" : 'Freedom of movement',
	"SL" : 'Pre-approved visa can be picked up on arrival.',
	"SM" : '',
	"SN" : '90 days',
	"SO" : '30 days, provided an invitation letter issued by the sponsor has been submitted to the Airport Immigration Department at least 2 days before arrival.',
	"SR" : '',
	"SS" : '',
	"ST" : '15 days',
	"SV" : '3 months',
	"SX" : 'Visa not required for 3 months.',
	"SY" : '',
	"SZ" : '30 days',
	"TC" : 'Visa not required for 90 days.',
	"TD" : '',
	"TF" : 'Special permit required',
	"TG" : '7 days',
	"TH" : '30 days by air, 15 days by land',
	"TJ" : '45 days',
	"TK" : 'All visitors must obtain a permit to enter Tokelau from the Tokelau Apia Liaison Office in Apia, at least 2 weeks prior to travel. Tokelau can only be reached by boat from Samoa and a permit from the Samoan Immigration Authorities is required to leave and re-enter Samoa.',
	"TL" : '30 days. Not available at all entry points.',
	"TM" : 'Pre-approved visa can be picked up on arrival.',
	"TN" : '3 months',
	"TO" : '31 days',
	"TR" : '3 months',
	"TT" : '90 days',
	"TV" : '1 month',
	"TW" : 'Visa not required for 90 days.',
	"TZ" : '',
	"UA" : '90 days',
	"UG" : '3 months',
	"UM-DQ" : 'Special permit required',
	"UM-FQ" : 'Special permit required',
	"UM-HQ" : 'Special permit required',
	"UM-JQ" : 'Special permit required',
	"UM-MQ" : 'Special permit required',
	"UM-WQ" : 'Special permit required',
	"US" : '90 days on arrival from overseas; ESTA (valid for 2 years when issued) required if arriving by air or cruise ship.',
	"UY" : '90 days',
	"UZ" : 'Pre-approved visa can be picked up on arrival.',
	"VA" : '',
	"VC" : '1 month',
	"VE" : '90 days',
	"VG" : 'Visa not required for 1 month (extendable).',
	"VI" : 'Visa not required under the Visa Waiver Program, for 90 days on arrival from overseas for 2 years. ESTA required.',
	"VN" : 'Pre-arranged visa obtained online through travel agencies available at Ho Chi Minh, Hanoi, Phu Quoc, or Danang. 30 day visa exemption at Phu Quoc Island.',
	"VU" : '30 days',
	"WF" : 'Nationals of the EU countries can enter and reside for an unlimited period without a visa in the French overseas departments and territories.',
	"WS" : '60 days',
	"YE" : '',
	"YT" : 'Nationals of the EU countries can enter and reside for an unlimited period without a visa in the French overseas departments and territories.',
	"ZA" : '90 days',
	"ZM" : '90 days as tourists, 30 days for business',
	"ZW" : '3 months. Strictly tourism purposes only.'
}